# Generated by Django 5.2.11 on 2026-02-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_extracharge_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="extracharge",
            name="split_by_ownership",
            field=models.BooleanField(
                default=True,
                help_text="If True, split charge by ownership percentages. If False, charge entirely to selected owner.",
            ),
        ),
    ]
