# Generated by Django 5.2.11 on 2026-02-11 18:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_horse_dam_horse_date_of_birth_horse_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicelineitem",
            name="ownership_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ownership percentage at time of invoice (for historical record)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="HorseOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ownership percentage (0.01 to 100.00)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "horse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerships",
                        to="core.horse",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horse_ownerships",
                        to="core.owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horse Ownership",
                "verbose_name_plural": "Horse Ownerships",
                "ordering": ["-start_date", "owner__name"],
            },
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="ownership",
            field=models.ForeignKey(
                blank=True,
                help_text="The ownership record this line item is based on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_items",
                to="core.horseownership",
            ),
        ),
    ]
