# Generated by Django 5.2.11 on 2026-02-11 18:04

from decimal import Decimal

from django.db import migrations


def populate_horse_ownership(apps, schema_editor):
    """Convert existing placements to 100% ownership records."""
    Placement = apps.get_model('core', 'Placement')
    HorseOwnership = apps.get_model('core', 'HorseOwnership')

    # Track processed horse/owner combinations to avoid duplicates
    processed = set()

    for placement in Placement.objects.select_related('horse', 'owner').order_by('start_date'):
        key = (placement.horse_id, placement.owner_id)
        if key in processed:
            continue

        # Find all placements for this horse/owner combination
        related_placements = Placement.objects.filter(
            horse=placement.horse,
            owner=placement.owner
        ).order_by('start_date')

        # Get the earliest start date and latest end date
        first = related_placements.first()
        last = related_placements.last()

        # Create ownership record spanning from first placement to last
        HorseOwnership.objects.create(
            horse_id=placement.horse_id,
            owner_id=placement.owner_id,
            percentage=Decimal('100.00'),
            start_date=first.start_date,
            end_date=last.end_date,  # None if still active
        )

        processed.add(key)


def reverse_populate_horse_ownership(apps, schema_editor):
    """Remove auto-created ownership records."""
    HorseOwnership = apps.get_model('core', 'HorseOwnership')
    # Delete records with exactly 100% ownership (assumed to be auto-created)
    HorseOwnership.objects.filter(percentage=Decimal('100.00')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_invoicelineitem_ownership_percentage_horseownership_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_horse_ownership, reverse_populate_horse_ownership),
    ]
