# Generated by Django 5.2.11 on 2026-02-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_fractional_ownership"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="placement",
            index=models.Index(
                fields=["horse", "end_date"], name="placement_horse_end_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="placement",
            index=models.Index(fields=["end_date"], name="placement_end_date_idx"),
        ),
    ]
